### ISSUE TITLE
Add Option to Have Normal IGT

### ISSUE THREAD

**Issue by TrevorBushnell** [CalebAP/PracticeSMBW#9]
It would be helpful to not have the timer on all levels set to 999. If there's a way to make an option to turn on/off 999 IGT that would be swell. That way players can still see if they are meeting certain IGT times.

**Comment by CalebAP** [comment]
Since the IGT starts at 900, not 999, you can simply ignore the first digit of the timer and the rest would be the same as normal, allowing you to see what IGT you'd get on the original game.
